// Chat connector (contract §2 chat source amendment, ADR-0013).
// Ingests chat distillation documents staged by the UI portal in inbox-chat/,
// validates the [T-n] reference chain fail-closed, mints the identity quintuple,
// and lands them in raw/chat/. Staged files are owned by the portal (it cleans
// them up after a successful run); this connector only reads them.
import fs from 'node:fs';
import path from 'node:path';
import { sha256, upsertRawDoc } from '../lib/rawdoc.mjs';
import { appendLog } from '../lib/log.mjs';

export const CONNECTOR_ID = 'chat@1.0.0';

// Deliberate duplication (no shared lib between services): these anchors are
// generated by the agent's distill-chat task and pre-checked by the portal's
// ui/lib/distill.mjs — keep all copies in sync by hand.
export const APPENDIX_MARKER = '<!-- transcript-appendix -->';
const ENTRY_RE = /^### \[T(\d+)\] (\w+) · (.+)$/gm;
const REF_RE = /\[T(\d+)\]/g;

/**
 * Parse and validate a staged chat distillation document (fail-closed: any
 * violation throws, the caller skips the file). Returns the derived identity
 * parts. The appendix block (marker line → EOF) is what source_id hashes, so
 * re-distilling the same conversation lands on the same document.
 */
export function parseDistillationDoc(rawText) {
  const text = rawText.replace(/\r\n/g, '\n');
  if (text.startsWith('---')) {
    throw new Error('staged document must not carry frontmatter (the connector mints it)');
  }
  const markerIdx = text.indexOf(APPENDIX_MARKER);
  if (markerIdx < 0) {
    throw new Error(`missing transcript appendix marker (${APPENDIX_MARKER})`);
  }
  const bodyPart = text.slice(0, markerIdx);
  const appendixPart = text.slice(markerIdx).replace(/^.*\n/, ''); // entries after the marker line

  const titleMatch = bodyPart.match(/^#\s+(.+)$/m);
  if (!titleMatch) throw new Error('missing H1 title');

  const entries = [...appendixPart.matchAll(ENTRY_RE)]
    .map((m) => ({ n: Number(m[1]), role: m[2], ts: m[3].trim() }));
  if (!entries.length) throw new Error('transcript appendix has no entries');
  entries.forEach((e, i) => {
    if (e.n !== i + 1) throw new Error(`appendix numbering broken at [T${e.n}] (expected T${i + 1})`);
  });

  const refs = [...new Set([...bodyPart.matchAll(REF_RE)].map((m) => Number(m[1])))];
  if (!refs.length) throw new Error('distilled body carries no [T-n] reference markers');
  for (const r of refs) {
    if (r < 1 || r > entries.length) {
      throw new Error(`unresolvable reference [T${r}] (appendix has ${entries.length} entries)`);
    }
  }

  const lastTs = entries[entries.length - 1].ts;
  return {
    title: titleMatch[1].trim(),
    messageCount: entries.length,
    // source_version = last message time; degrade to null (caller falls back
    // to the staged file's mtime) when the entry carries no usable timestamp
    lastTs: Number.isNaN(Date.parse(lastTs)) ? null : lastTs,
    transcriptHash: sha256(appendixPart.trim()),
    body: text.replace(/[ \t]+$/gm, '').trim() + '\n',
  };
}

export function run(kbRoot, { inbox }) {
  const summary = { created: [], updated: [], unchanged: [], unsupported: [], errors: [], total: 0 };
  if (!fs.existsSync(inbox)) return summary; // no staging yet is a normal state

  for (const e of fs.readdirSync(inbox, { withFileTypes: true })) {
    if (!e.isFile()) continue; // flat staging only
    if (!e.name.toLowerCase().endsWith('.md')) {
      summary.unsupported.push(e.name);
      continue;
    }
    summary.total++;
    const absPath = path.join(inbox, e.name);
    try {
      const doc = parseDistillationDoc(fs.readFileSync(absPath, 'utf8'));
      const sourceId = `conv-${doc.transcriptHash.slice(0, 8)}`;
      const stat = fs.statSync(absPath);
      const result = upsertRawDoc(kbRoot, {
        source: 'chat',
        sourceId,
        fileName: `${sourceId}.md`, // pure identity — the LLM title is unstable
        sourceUrl: `weft://chat/${sourceId}`,
        sourceVersion: doc.lastTs || stat.mtime.toISOString(),
        title: doc.title,
        connector: CONNECTOR_ID,
        extra: { message_count: doc.messageCount, staged_path: e.name.replace(/\\/g, '/') },
        contentHash: sha256(doc.body),
        body: doc.body,
      });
      summary[result.action === 'created' ? 'created' : result.action === 'updated' ? 'updated' : 'unchanged']
        .push(result.relPath.replace(/\\/g, '/'));
      if (result.action !== 'unchanged') {
        appendLog(kbRoot, 'acquire', `chat:${result.action}`, result.relPath.replace(/\\/g, '/'), `from ${e.name.replace(/\\/g, '/')}`);
      }
    } catch (err) {
      summary.errors.push({ file: e.name, error: err.message }); // fail-closed skip
    }
  }
  return summary;
}
