// ADR-0013: one-click chat distillation — portal orchestration.
// Flow (inside the per-KB serial queue): transcript → agent distill-chat task
// (the only model call) → portal pre-check (fail-closed reference validation,
// layer 1) → stage into inbox-chat/ → spawn `acquire chat` (the connector
// re-validates, layer 2, and lands raw/chat/) → clean up the staged file.
// The portal never writes raw/ — the acquisition CLI is the only writer.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { spawnJob } from './jobs.mjs';
import { agentTaskIO, agentTaskSpawn } from './agentcli.mjs';

const ACQUIRE = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'acquisition', 'scripts', 'acquire.mjs',
);

// Deliberate duplication (no shared lib between services): these anchors are
// generated by agent/weft_agent/tasks/distill_chat.py and re-validated by
// acquisition/scripts/connectors/chat.mjs — keep all copies in sync by hand.
const APPENDIX_MARKER = '<!-- transcript-appendix -->';
const ENTRY_RE = /^### \[T(\d+)\] (\w+) · (.+)$/gm;
const REF_RE = /\[T(\d+)\]/g;

const MAX_MESSAGES = 200;
const MAX_TRANSCRIPT_CHARS = 30000; // mirrors distill_chat.MAX_TRANSCRIPT_CHARS

function sha256(s) {
  return crypto.createHash('sha256').update(s, 'utf8').digest('hex');
}

/**
 * Portal pre-check (fail-closed layer 1), run BEFORE anything touches disk.
 * Mirrors the connector's parseDistillationDoc plus the one check only the
 * portal can make: appendix entry count === the transcript's message count.
 * Returns the transcript hash (same recipe as the connector) on success.
 */
export function validateDistilled(rawText, expectedCount) {
  const text = String(rawText || '').replace(/\r\n/g, '\n');
  if (!text.trim()) throw new Error('蒸馏结果为空,请重试');
  if (text.startsWith('---')) throw new Error('蒸馏结果携带 frontmatter,已拒绝,请重试');
  const idx = text.indexOf(APPENDIX_MARKER);
  if (idx < 0) throw new Error('蒸馏结果缺少转录附录,请重试');
  const bodyPart = text.slice(0, idx);
  const appendixPart = text.slice(idx).replace(/^.*\n/, '');

  const entries = [...appendixPart.matchAll(ENTRY_RE)].map((m) => Number(m[1]));
  if (entries.length !== expectedCount) {
    throw new Error(`转录附录条数(${entries.length})与对话消息数(${expectedCount})不一致,请重试`);
  }
  entries.forEach((n, i) => {
    if (n !== i + 1) throw new Error('转录附录编号断裂,请重试');
  });
  const refs = [...new Set([...bodyPart.matchAll(REF_RE)].map((m) => Number(m[1])))];
  if (!refs.length) throw new Error('蒸馏正文没有任何引用标记,请重试');
  for (const r of refs) {
    if (r < 1 || r > entries.length) throw new Error(`蒸馏正文引用了不存在的 [T${r}],请重试`);
  }
  return { transcriptHash: sha256(appendixPart.trim()) };
}

export function distillJob(kb, { messages }) {
  if (!Array.isArray(messages) || !messages.length) throw new Error('messages must be a non-empty array');
  if (messages.length > MAX_MESSAGES) throw new Error(`一次最多整理 ${MAX_MESSAGES} 条消息`);
  const clean = messages.map((m, i) => {
    const role = m && m.role === 'assistant' ? 'assistant' : 'user';
    const text = String((m && m.text) || '').trim();
    if (!text) throw new Error(`第 ${i + 1} 条消息为空`);
    const ts = m && typeof m.ts === 'string' && m.ts ? m.ts : undefined;
    return ts ? { role, text, ts } : { role, text };
  });
  const total = clean.reduce((n, m) => n + m.text.length, 0);
  if (total > MAX_TRANSCRIPT_CHARS) {
    throw new Error(`对话过长(约 ${total} 字符,上限 ${MAX_TRANSCRIPT_CHARS}),请先清空后分段整理。`);
  }

  return {
    type: 'distill-chat',
    label: `一键整理对话(${clean.length} 条)→ raw/chat/`,
    run: async (job) => {
      // 1. distill via the agent service (all model calls live there)
      const io = agentTaskIO(kb, 'distill', { messages: clean });
      let out;
      try {
        const agent = agentTaskSpawn();
        await spawnJob(job, agent.command, [...agent.baseArgs, 'distill-chat', '--kb', kb,
          '--input-file', io.inputFile, '--output-file', io.outputFile], { cwd: agent.cwd });
        out = JSON.parse(fs.readFileSync(io.outputFile, 'utf8'));
      } finally {
        io.cleanup(); // failure leaves no scratch behind
      }

      // 2. portal pre-check — before anything touches the staging area
      const { transcriptHash } = validateDistilled(out.body, clean.length);

      // 3. stage (same staged name per conversation → re-distillation overwrites)
      const inboxDir = path.join(kb, 'inbox-chat');
      fs.mkdirSync(inboxDir, { recursive: true });
      const stagedName = `conv-${transcriptHash.slice(0, 8)}.md`;
      const stagedPath = path.join(inboxDir, stagedName);
      fs.writeFileSync(stagedPath, out.body, 'utf8');

      // 4. the connector lands it in raw/chat/ (fail-closed layer 2)
      const { log } = await spawnJob(job, process.execPath, [ACQUIRE, 'chat', '--kb', kb]);
      let summary;
      try { summary = JSON.parse(log.slice(log.indexOf('{'))); }
      catch { throw new Error('连接器输出无法解析,请查看作业日志'); }
      const mine = (summary.errors || []).find((e) => e.file === stagedName);
      if (mine) {
        try { fs.unlinkSync(stagedPath); } catch { /* best-effort: no half-product */ }
        throw new Error(`连接器校验拒绝:${mine.error}`);
      }
      const sourceId = `conv-${transcriptHash.slice(0, 8)}`;
      const rel = `raw/chat/${sourceId}.md`;
      const action = (summary.created || []).includes(rel) ? 'created'
        : (summary.updated || []).includes(rel) ? 'updated' : 'unchanged';

      // 5. success — the staged file is consumed; remove it
      try { fs.unlinkSync(stagedPath); } catch { /* a leftover re-processes as unchanged */ }
      return { path: rel, title: out.title || '', action };
    },
  };
}
